** Nympy for scientific Computing! **
The element of the numpy are all required to be of the same data type!

In [5]:
import numpy as np;


In [7]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [11]:
b=np.arange(1,11,2) # same as range function
print(b)

[1 3 5 7 9]


In [15]:
c=np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
d=np.array([[1,2,3],[4,5,6]])
print(d)
print("Dimention of the array is :",d.ndim)
print("Shape of the array is : ",d.shape)
print("Size of the array is : ",d.size)
print("Data type of the array is :",d.dtype)

[[1 2 3]
 [4 5 6]]
Dimention of the array is : 2
Shape of the array is :  (2, 3)
Size of the array is :  6
Data type of the array is : int64


In [30]:
print("The number in the array which is greater than 4")
d>4

The number in the array which is greater than 4


array([[False, False, False],
       [False,  True,  True]])

In [35]:
#vector operation : are the operation which is applied on the two np vector
a1=np.array([1,2,3,4,5,6,7,8])
a2=np.array([1,2,3,4,5,6,7,8])
print(a1+a2) #this is only for when they both have the same dimention!

[ 2  4  6  8 10 12 14 16]


In [72]:
# Array functions
import random
# randome number from 1 to 99 of size 10
a1=np.random.randint(1,100,size=10)
a1

array([72,  4, 33, 76, 37,  1, 90, 27, 33, 32])

In [80]:
arr=np.array([i for i in range(10)])
print("The give array is ",arr)
print("max : ",np.max(arr))
print("Sum : ",np.sum(arr))

The give array is  [0 1 2 3 4 5 6 7 8 9]
max :  9
Sum :  45


In [86]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Sum of cols ",np.sum(mat,axis=0));
# o = rows 
print("Sum of first row ",np.sum(mat[0,:]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of cols  [12 15 18]
Sum of first row  6


In [88]:
a1=np.array([[1,2,3],[1,2,3],[1,2,3]])
a2=np.array([[1,2,3],[1,2,3],[1,2,3]])
a3=np.dot(a1,a2)
print(a3)

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [95]:
# Indexing and slicing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [104]:
print(a1)
print(a1[2:6]) #last one is not included!

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [109]:
print(a2)
print(a2[1,2]) #find the location of 6
print(a2[1,:]) #find all the element in the 2nd row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]


In [114]:
print(a2[1:,1:3])
#problem:- print all the corners of the square.
print(a2[::2,::3])

[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]


In [117]:
print(a2[::2,::2])

[[ 0  2]
 [ 8 10]]


In [123]:
#iterating
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [126]:
a2
for i in a2:
    print(i)
np.transpose(a2)
# shorthand for transpose
a2.T

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [127]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [136]:
# Stacking - to combine multiple data togeather!
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [137]:
print(a5)
a6=np.hstack((a4,a5))
print(a6)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [138]:
a7=np.vstack((a4,a5))
print(a7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
